// Auto-Generated by FAKE; do not edit
// <auto-generated/>
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyTitle("PrivacyGate API for .NET")]
[assembly: AssemblyProduct("PrivacyGate")]
[assembly: AssemblyCompany("Brian Chavez")]
[assembly: AssemblyCopyright("Brian Chavez © 2015")]
[assembly: AssemblyVersion("0.0.0")]
[assembly: AssemblyFileVersion("0.0.0")]
[assembly: AssemblyInformationalVersion("0.0.0-localbuild built on 1/1/2015 12:00:00 AM")]
[assembly: AssemblyTrademark("MIT License")]
[assembly: AssemblyDescription("https://github.com/privacyshore/PrivacyGate-dotnet")]
[assembly: InternalsVisibleTo("PrivacyGate.Tests")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "PrivacyGate API for .NET";
        internal const System.String AssemblyProduct = "PrivacyGate";
        internal const System.String AssemblyCompany = "";
        internal const System.String AssemblyCopyright = "";
        internal const System.String AssemblyVersion = "0.0.0";
        internal const System.String AssemblyFileVersion = "0.0.0";
        internal const System.String AssemblyInformationalVersion = "0.0.0-localbuild built on 1/1/2015 12:00:00 AM";
        internal const System.String AssemblyTrademark = "MIT License";
        internal const System.String AssemblyDescription = "https://github.com/privacyshore/PrivacyGate-dotnet";
        internal const System.String InternalsVisibleTo = "PrivacyGate.Tests";
    }
}
